#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StajBilgisi.Resource", IsApplication=true)]

namespace StajBilgisi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int my_blue = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int my_gray = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int my_gray2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int my_purple = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonFirmalariListeleStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonGirisKayitStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonGirisStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonKayitEkleStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ButtonKayitStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ButtonYorumlariGorStyle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int edit_text_style = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int forsearch = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_search = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int login = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pen = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pen2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ProgressBarStyle = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int refresh = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int btnDialogGirisYap = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int btnDialogKayıtOl = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int btnFirmalariListele = 2131296268;
			
			// aapt resource value: 0x7f090028
			public const int btnGiris = 2131296296;
			
			// aapt resource value: 0x7f09000d
			public const int btnKayitEkle = 2131296269;
			
			// aapt resource value: 0x7f09001b
			public const int btnKayitOlustur = 2131296283;
			
			// aapt resource value: 0x7f09002a
			public const int btnKayıtOl = 2131296298;
			
			// aapt resource value: 0x7f09000e
			public const int btnYorumlarimiGor = 2131296270;
			
			// aapt resource value: 0x7f090005
			public const int edtAd = 2131296261;
			
			// aapt resource value: 0x7f09000a
			public const int edtBolum = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int edtCinsiyet = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int edtIL = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int edtIlce = 2131296265;
			
			// aapt resource value: 0x7f090013
			public const int edtKayitEkleCalisanSayisi = 2131296275;
			
			// aapt resource value: 0x7f090011
			public const int edtKayitEkleKurumAdi = 2131296273;
			
			// aapt resource value: 0x7f090019
			public const int edtKayitEkleKurumAdres = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int edtKayitEkleKurumDepartman = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int edtKayitEkleKurumGorev = 2131296279;
			
			// aapt resource value: 0x7f09001a
			public const int edtKayitEkleKurumYorum = 2131296282;
			
			// aapt resource value: 0x7f090003
			public const int edtKullaniciAd = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int edtKullaniciAdiGirisDialog = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int edtKullaniciSifre = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int edtKullaniciSifreGirisDialog = 2131296257;
			
			// aapt resource value: 0x7f09001e
			public const int edtSearch = 2131296286;
			
			// aapt resource value: 0x7f090006
			public const int edtSoyad = 2131296262;
			
			// aapt resource value: 0x7f09001d
			public const int listView = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int llContainer = 2131296284;
			
			// aapt resource value: 0x7f09002b
			public const int progressBar1 = 2131296299;
			
			// aapt resource value: 0x7f09002d
			public const int refreshh = 2131296301;
			
			// aapt resource value: 0x7f09000f
			public const int scrollView1 = 2131296271;
			
			// aapt resource value: 0x7f09002c
			public const int search = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int search2 = 2131296302;
			
			// aapt resource value: 0x7f090010
			public const int textView1 = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int textView2 = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int textView3 = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int textView4 = 2131296278;
			
			// aapt resource value: 0x7f090018
			public const int textView5 = 2131296280;
			
			// aapt resource value: 0x7f090021
			public const int txtCalisanSayisi = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int txtDepartman = 2131296288;
			
			// aapt resource value: 0x7f090027
			public const int txtHosgeldiniz = 2131296295;
			
			// aapt resource value: 0x7f090023
			public const int txtIlgiliYorum = 2131296291;
			
			// aapt resource value: 0x7f09001f
			public const int txtKurumadi = 2131296287;
			
			// aapt resource value: 0x7f090022
			public const int txtSorumluluk = 2131296290;
			
			// aapt resource value: 0x7f090029
			public const int txtVeya = 2131296297;
			
			// aapt resource value: 0x7f090025
			public const int txtYorumAdres = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int txtYorumGozuken = 2131296292;
			
			// aapt resource value: 0x7f090026
			public const int txtYorumTarih = 2131296294;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_giris_yap = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_kayit_ol = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GirisEkrani = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int kayitEkle = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int liste = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listeyardimci = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int listeYorum = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int actionbar2 = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int MyCustomTheme1 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int dialog_animation2 = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
